services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: product-service
      POSTGRES_USER: piseth@12345
      POSTGRES_PASSWORD: 123456
    ports:
      - "2345:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: