spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:2345/product-service
    username: piseth@12345
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/